[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
name = "worker-plus-build"
version = "0.0.8"
license = "Apache-2.0"
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-build"
readme = "README.md"
description = "This is a tool to be used as a custom build command for a Cloudflare Workers `workers-rs` project."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
dirs-next = "2.0.0"
flate2 = "1.0.24"
tar = "0.4.38"
ureq = { version = "2.4.0", features = ["tls", "gzip"] }

[dev-dependencies]
wasm-bindgen-cli-support = "0.2.80"
