[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
name = "worker-plus-sandbox"
version = "0.1.0"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
blake2 = "0.10.4"
chrono = { version = "0.4.22", default-features = false, features = [
    "wasmbind",
    "clock",
] }
cfg-if = "1.0.0"
console_error_panic_hook = { version = "0.1.7", optional = true }
getrandom = { version = "0.2.6", features = ["js"] }
hex = "0.4.3"
http = "0.2.8"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
worker = { path = "../worker", version = "0.0.13", package = "worker-plus" }
futures-channel = "0.3.21"
futures-util = { version = "0.3.21", default-features = false }
rand = "0.8.5"
serde-wasm-bindgen = "0.4.3"

[dev-dependencies]
futures-channel = { version = "0.3.21", features = ["sink"] }
futures-util = { version = "0.3.21", default-features = false, features = ["sink"] }
reqwest = { version = "0.11.10", features = [
    "blocking",
    "json",
    "multipart",
    "stream",
] }
tokio = { version = "1.19.2", features = ["macros", "rt", "test-util"] }
tungstenite = "0.17.2"
wasm-bindgen-test = "0.3.30"
