name = "testing-rust-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-09-12" # required
compatibility_flags = ["streams_enable_constructors"]

kv_namespaces = [
    { binding = "SOME_NAMESPACE", id = "", preview_id = "" },
    { binding = "FILE_SIZES", id = "", preview_id = "" },
]

vars = { SOME_VARIABLE = "some value" }

[[services]]
binding = "remote"
service = "remote-service"

[miniflare.mounts]
remote-service = "./remote-service"

[durable_objects]
bindings = [{ name = "COUNTER", class_name = "Counter" }, { name = "ALARM", class_name = "AlarmObject" }]

[[queues.consumers]]
 queue = "my_queue"

[[queues.producers]]
 queue = "my_queue"
 binding = "my_queue"

[[r2_buckets]]
binding = 'EMPTY_BUCKET'
bucket_name = ''
preview_bucket_name = 'empty_bucket'

[[r2_buckets]]
binding = 'PUT_BUCKET'
bucket_name = ''
preview_bucket_name = 'put_bucket'

[[r2_buckets]]
binding = 'SEEDED_BUCKET'
bucket_name = ''
preview_bucket_name = 'seeded_bucket'

[[r2_buckets]]
binding = 'DELETE_BUCKET'
bucket_name = ''
preview_bucket_name = 'delete_bucket'

[build]
command = "worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
